config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do

  root 'dashboard#index'
  mount Sidekiq::Web, at: '/sidekiq'

  resources :searches
  resources :sessions
  resources :users do
    resources :photos
    resources :signatures
  end

  namespace :api do
    resources :sessions, only: %i(index)
    resources :searches, only: %i(create)
    resources :users, only: %i(create show) do
      resources :photos, only: %i(create show)
      resources :signatures, only: %i(create show)
      resources :session_histories, only: %i(create show)
    end
  end
end

app/models/signature.rb
class Signature < ApplicationRecord
  belongs_to :user
  mount_base64_uploader :image, ImageUploader

  attribute :uuid, :string, default: -> { SecureRandom.uuid }

  after_save :save_name

  def save_name
    user.update_attribute(:name, name) if user.present?
  end
end

app/controllers/signatures_controller.rb
class SignaturesController < ApplicationController
  before_action :set_user
  before_action :set_signature, only: [:show, :edit, :update, :destroy]
  skip_before_action :basic_auth, only: [:new, :create] unless Rails.env.development?

  def index
    @signatures = @user.signatures
  end

  def show
  end

  def new
    @signature = @user.signatures.new
    render layout: false
  end

  def edit
  end

  def create
    @signature = @user.signatures.new(signature_params)
    if @signature.save
      ActionCable.server.broadcast 'user_channel', message: 'reload'
      head :created
    else
      render :new
    end
  end

  def update
    if @signature.update(signature_params)
      redirect_to [@user, @signature], notice: 'Signature was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @signature.destroy
    redirect_to user_signatures_url(@user), notice: 'Signature was successfully destroyed.'
  end

  private
  def set_user
    @user = User.find(params[:user_id])
  end

  def set_signature
    @signature = @user.signatures.find(params[:id])
  end

  def signature_params
    params.require(:signature).permit(:image, :name)
  end
end

app/views/signatures/_form.html.erb
<%= form_for [@user, @signature], :html => { :class => "form-horizontal signature" } do |f| %>

  <% if @signature.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@signature.errors.count, "error") %> prohibited this signature from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @signature.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :image, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.file_field :image, :class => 'form-control' %>
    </div>
    <%=f.error_span(:image) %>
  </div>
  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                user_signatures_path(@user), :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/signatures/edit.html.erb
<%- model_class = Signature -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/signatures/index.html.erb
<%- model_class = Signature -%>
<div class="page-header">
  <h1><%= t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
  <tr>
    <th><%= model_class.human_attribute_name(:id) %></th>
    <th><%= model_class.human_attribute_name(:user_id) %></th>
    <th><%= model_class.human_attribute_name(:image) %></th>
    <th><%= model_class.human_attribute_name(:name) %></th>
    <th><%= t '.actions', :default => t("helpers.actions") %></th>
  </tr>
  </thead>
  <tbody>
  <% @signatures.each do |signature| %>
      <tr>
        <td><%= link_to signature.id, user_signature_path(@user,signature) %></td>
        <td><%= signature.user_id %></td>
        <td><%= image_tag signature.image.thumb %></td>
        <td><%= signature.name %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      user_signature_path(@user, signature), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_user_signature_path(@user, signature), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      user_signature_path(@user, signature),
                      :method => :delete,
                      :data => {:confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?'))},
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_user_signature_path(@user),
            :class => 'btn btn-primary' %>

app/views/signatures/new.html.erb
<!doctype html>
<html>
<head>
  <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="mobile-web-app-capable" content="yes">
  <meta name="HandheldFriendly" content="true"/>
  <title>myscript-text demo</title>
  <script src="<%= Settings.signature_cdn_base %>/bower_components/webcomponentsjs/webcomponents-lite.js"></script>
  <link rel="import" href="<%= Settings.signature_cdn_base %>/myscript-text-web.html">
  <style is="custom-style" include="iron-flex"></style>
</head>
<style>
  body {
    margin: 0;
    height: 100vh;
  }
  myscript-text-web {
    height: 100%;
  }
  paper-menu-button {
    padding: 0;
    width: 250px;
  }
</style>
<body touch-action="none" unresolved>

<template id="app" is="dom-bind">
  <myscript-text-web id="text-input"
                     host="webdemoapi.myscript.com"
                     applicationkey="<%= Settings.myscript.applicationkey %>"
                     hmackey="<%= Settings.myscript.hmackey %>"
                     recognitioncandidates="1"
                     language="ja_JP">
  </myscript-text-web>
</template>
<%= form_for [@user, @signature], :html => { :class => "form-horizontal signature" } do |f| %>
 <%= f.text_field :name %>
 <%= f.text_field :image %>
<% end %>
</body>
</html>

app/views/signatures/show.html.erb
<%- model_class = Signature -%>
<div class="page-header">
  <h1><%= t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @signature.user_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:image) %>:</strong></dt>
  <dd><%= image_tag @signature.image %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @signature.name %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
            user_signatures_path(@user), :class => 'btn btn-default' %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
            edit_user_signature_path(@user, @signature), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
            user_signature_path(@user, @signature),
            :method => 'delete',
            :data => {:confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?'))},
            :class => 'btn btn-danger' %>