config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do

  root 'dashboard#index'
  mount Sidekiq::Web, at: '/sidekiq'

  resources :searches
  resources :sessions
  resources :users do
    resources :photos
    resources :signatures
  end

  namespace :api do
    resources :sessions, only: %i(index)
    resources :searches, only: %i(create)
    resources :users, only: %i(create show) do
      resources :photos, only: %i(create show)
      resources :signatures, only: %i(create show)
      resources :session_histories, only: %i(create show)
    end
  end
end

app/models/user.rb
class User < ApplicationRecord

  has_many :photos, dependent: :destroy
  has_many :signatures, dependent: :destroy
  has_many :visit_histories, dependent: :destroy
  has_many :session_histories, dependent: :destroy
  has_many :sessions, :through => :session_histories

  after_create :visit

  def visit
    self.visit_histories.create
  end
end

app/controllers/api/users_controller.rb
module Api
  class UsersController < Api::ApplicationController
    before_action :set_user, only: [:show, :edit, :update, :destroy]

    def index
      @users = User.includes(:photos).order(id: :desc).page params[:page]
      render json: @users
    end

    def show
      render json: @user
    end

    def create
      @user = User.new
      if @user.save
        render json: @user
      else
        render json: @user.errors, status: :unprocessable_entity
      end
    end

    def update
      if @user.update(user_params)
        render json: @user
      else
        render json: @user.errors, status: :unprocessable_entity
      end
    end

    def destroy
      @user.destroy
      head :no_content
    end

    private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.includes(:photos, :visit_histories, :session_histories).order(id: :desc).page params[:page]
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    DeleteUserJob.perform_later(@user)
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name)
  end
end

app/views/users/_form.html.erb
<%= form_for @user, :html => { :class => "form-horizontal user" } do |f| %>

  <% if @user.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                users_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/index.html.erb
<div class="page-header">
  <h1>来場者一覧</h1>
</div>

<%= paginate @users %>
<table class="table table-striped">
  <thead>
  <tr>
    <th>ID</th>
    <th>写真</th>
    <th>名前</th>
    <th>申込みセッション数</th>
    <th>来場回数</th>
    <th>作成日時</th>
    <th><%= t '.actions', :default => t("helpers.actions") %></th>
  </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= link_to user_photos_path(user) do %>
              <% photo = user.photos.first %>
              <%= image_tag photo.image.thumb.url if photo.present? %>
          <% end %>
        </td>
        <td><%= user.name %></td>
        <td><%= user.session_histories.size %></td>
        <td><%= user.visit_histories.size %></td>
        <td><%= l user.created_at %></td>
        <td>
          <%= link_to '写真',
                      user_photos_path(user), :class => 'btn btn-default btn-xs' %>
          <%= link_to '署名',
                      user_signatures_path(user), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_user_path(user), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      user_path(user),
                      :method => :delete,
                      :data => {:confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?'))},
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_user_path,
            :class => 'btn btn-primary' %>

app/views/users/new.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/show.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @user.name %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              users_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_user_path(@user), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              user_path(@user),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>