config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do

  root 'dashboard#index'
  mount Sidekiq::Web, at: '/sidekiq'

  resources :searches
  resources :sessions
  resources :users do
    resources :photos
    resources :signatures
  end

  namespace :api do
    resources :sessions, only: %i(index)
    resources :searches, only: %i(create)
    resources :users, only: %i(create show) do
      resources :photos, only: %i(create show)
      resources :signatures, only: %i(create show)
      resources :session_histories, only: %i(create show)
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "Kaopass" %></title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
  <![endif]-->
</head>
<body>

<div class="navbar navbar-default navbar-static-top">
  <div class="container">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="<%= root_path %>">KaoPass</a>
    <div class="navbar-collapse collapse navbar-responsive-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "Users", users_path %></li>
        <li><%= link_to "Session", sessions_path %></li>
      </ul>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <%= bootstrap_flash %>
      <%= yield %>
    </div>

  </div><!--/row-->

  <footer>
    <p>&copy; Company 2017</p>
  </footer>

</div> <!-- /container -->

</body>
</html>